application: skeleton-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- static/.tmp/.*
- static/app_/.*
- static/partial_/.*
- static/node_modules/.*
- static/bower_components/.*
- static/rest_framework/.*
- static/test/.*
- static/Gruntfile.js
- static/package.json

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: gae.main.app

builtins:
- deferred: on

libraries:
- name: django
  version: "1.5"
- name: PIL
  version: latest
- name: ssl
  version: latest

env_variables:
  SECRET_KEY: 'k37x^j1-vf9^0639a#fk5xk$9leff&fr@2%^j%l^!h0+#ca9rw'
  SETTINGS_MODE: 'DEV'
  TWILIO_ACCOUNT_SID: 'ACed0b9130dd0dc916600d385c4a156cc3'
  TWILIO_AUTH_TOKEN: '44c48068997c562b713ff17fdb396046'
  TWILIO_APP_NUMBER: '+441332402461'
